Repository Teamable-Analytics/algorithms, pull requests merged in 2023-11, with the labels that each got.

#189 Added option to save graphs
  benchmarking/evaluations/graphing/line_graph.py
  benchmarking/evaluations/graphing/line_graph_metadata.py
Labels: bug, enhancement

#181 Fix Runs With Cashing
  benchmarking/runs/concentrate_gpa.py
  benchmarking/runs/concentrate_many_attributes.py
  benchmarking/runs/diversify_gender_min_2.py
  benchmarking/runs/include_social_friends.py
  benchmarking/runs/three_tokenization_constraints.py
Labels: enhancement, blocking

#236 Fixed bug related to student friend/enemies not being counted correctly
  benchmarking/evaluations/metrics/utils/student_calculations.py
Labels: bug

#237 Create New Scenarios to Benchmark Priority
  api/models/enums.py
  benchmarking/evaluations/goals.py
  benchmarking/evaluations/scenarios/project_location.py
  benchmarking/evaluations/scenarios/project_requirement_preferences_diversify_gender.py
Labels: benchmarking

#234 mock student generator bug fix
  benchmarking/data/simulated_data/mock_student_provider.py
  tests/test_benchmarking/test_data/test_simulated_data/test_mock_student_provider.py
Labels: bug

#244 Fix graphing tool not creating driectory where it wants to save the graph
  benchmarking/evaluations/graphing/line_graph.py
Labels: bug

#246 Close plot after showing or saving
  benchmarking/evaluations/graphing/line_graph.py
Labels: bug

#239 Benchmark social algorithm with different parameters
  benchmarking/evaluations/scenarios/give_the_people_what_they_want.py
  benchmarking/runs/social/__init__.py
  benchmarking/runs/social/scoial_run.py
  benchmarking/runs/social/varied_class_size.py
  benchmarking/runs/social/varied_num_enemies.py
  benchmarking/runs/social/varied_num_friends.py
  benchmarking/runs/social/varied_team_size.py
Labels: benchmarking

#252 RIP GiveThePeopleWhatTheyWant
  benchmarking/evaluations/scenarios/include_friends_exclude_enemies.py
  benchmarking/runs/social/varied_class_size.py
  benchmarking/runs/social/varied_num_enemies.py
  benchmarking/runs/social/varied_num_friends.py
  benchmarking/runs/social/varied_team_size.py
Labels: bug, invalid

#230 Envy-freeness up to 1 item (EF1) metric
  benchmarking/evaluations/metrics/envy_free_up_to_one_item.py
  tests/test_benchmarking/test_evaluations/test_metrics/test_envy_freeness_up_to_one_item.py
Labels: enhancement, benchmarking

#247 Envy-freeness (EF) metric
  benchmarking/evaluations/metrics/envy_freeness.py
  tests/test_benchmarking/test_evaluations/test_metrics/test_envy_freeness.py
Labels: enhancement, benchmarking

#248 Proportionality (PROP) metric
  benchmarking/evaluations/metrics/proportionality.py
  tests/test_benchmarking/test_evaluations/test_metrics/test_proportionality.py
Labels: enhancement, benchmarking

#254 Add priority validation
  api/ai/interfaces/algorithm_options.py
  api/ai/priority_algorithm/priority/interfaces.py
  api/ai/priority_algorithm/priority/priority.py
  api/models/enums.py
  tests/test_api/test_ai/test_priority_algorithm/test_mutations/test_local_max.py
  tests/test_api/test_ai/test_priority_algorithm/test_mutations/test_robinhood.py
Labels: enhancement

#251 Write chunk() and combine() functions
  benchmarking/caching/simulation_cache.py
  benchmarking/caching/utils.py
  benchmarking/simulation/utils.py
  tests/test_benchmarking/test_caching/_data.py
  tests/test_benchmarking/test_caching/test_simulation_cache.py
  tests/test_benchmarking/test_caching/test_utils.py
  tests/test_benchmarking/test_simulation/test_utils.py
Labels: enhancement

#261 Refactor out old scenario name
  benchmarking/runs/social/varied_class_size.py
  benchmarking/runs/social/varied_num_enemies.py
  benchmarking/runs/social/varied_num_friends.py
  benchmarking/runs/social/varied_team_size.py
Labels: bug

#267 Use the correct number of friends for social runs
  benchmarking/runs/social/varied_class_size.py
  benchmarking/runs/social/varied_num_enemies.py
Labels: bug

#265 Fix calculation of max_team_size
  benchmarking/simulation/mock_algorithm.py
Labels: bug

#257 Use serializers in api data loader
  api/api/utils/generate_teams_data_loader.py
  api/models/student/serializer.py
  api/models/team/serializer.py
  api/models/team_set/serializer.py
Labels: benchmarking, api

#231 Benchmark Priority Algorithm Parameters with Diversify Gender Min 2 Scenario
  benchmarking/runs/priority_algorithm/__init__.py
  benchmarking/runs/priority_algorithm/diversify_gender_min_2/__init__.py
  benchmarking/runs/priority_algorithm/diversify_gender_min_2/class_size.py
  benchmarking/runs/priority_algorithm/diversify_gender_min_2/interfaces.py
  benchmarking/runs/priority_algorithm/diversify_gender_min_2/max_keep.py
  benchmarking/runs/priority_algorithm/diversify_gender_min_2/max_spread.py
  benchmarking/runs/priority_algorithm/diversify_gender_min_2/max_time.py
  benchmarking/runs/priority_algorithm/diversify_gender_min_2/num_iterations.py
Labels: benchmarking
