Repository Teamable-Analytics/algorithms, pull requests merged in 2023-10, with the labels that each got.

#114 Added a value error for 0 length metrics.
  benchmarking/simulation/simulation.py
Labels: enhancement, good first issue

#118 Implement Priority Satisfaction Metric
  benchmarking/evaluations/metrics/priority_satisfaction.py
  benchmarking/runs/diversify_gender_min_2.py
  benchmarking/simulation/goal_to_priority.py
  tests/test_benchmarking/test_evaluations/__init__.py
  tests/test_benchmarking/test_evaluations/test_metrics/__init__.py
  tests/test_benchmarking/test_evaluations/test_metrics/test_priority_satisfaction.py
  tests/test_benchmarking/test_simulation/test_goal_to_priority.py
Labels: enhancement

#132 Improve graphing tool
  benchmarking/evaluations/graphing/line_graph.py
  benchmarking/evaluations/graphing/line_graph_metadata.py
  benchmarking/evaluations/interfaces.py
  benchmarking/evaluations/metrics/average_gini_index.py
  benchmarking/evaluations/metrics/average_gini_index_multi_attribute.py
  benchmarking/evaluations/metrics/maximum_gini_index.py
  benchmarking/evaluations/metrics/minimum_gini_index.py
  benchmarking/evaluations/metrics/num_requirements_satisfied.py
  benchmarking/evaluations/metrics/num_teams_meeting_requirements.py
  benchmarking/evaluations/metrics/priority_satisfaction.py
  benchmarking/runs/concentrate_gpa.py
  benchmarking/runs/concentrate_many_attributes.py
  benchmarking/runs/diversify_gender_min_2.py
  benchmarking/runs/include_social_friends.py
  tests/test_benchmarking/test_simulation/test_simulation.py
Labels: enhancement

#149 basic simulation set rename
  benchmarking/runs/concentrate_gpa.py
  benchmarking/runs/concentrate_many_attributes.py
  benchmarking/runs/diversify_gender_min_2.py
  benchmarking/runs/include_social_friends.py
  benchmarking/runs/three_tokenization_constraints.py
  benchmarking/simulation/basic_simulation_set.py
  benchmarking/simulation/basic_simulation_set_2.py
  benchmarking/simulation/mock_algorithm_2.py
  tests/test_benchmarking/test_simulation/test_basic_simulation_set.py
Labels: enhancement

#150 create singular simulation class
  benchmarking/simulation/basic_simulation_set.py
  benchmarking/simulation/simulation.py
  benchmarking/simulation/simulation_settings.py
  tests/test_benchmarking/test_simulation/_data.py
  tests/test_benchmarking/test_simulation/test_basic_simulation_set.py
  tests/test_benchmarking/test_simulation/test_simulation.py
Labels: enhancement

#137 Add more customizability to graphs
  benchmarking/evaluations/graphing/graph_metadata.py
  benchmarking/evaluations/graphing/line_graph.py
Labels: enhancement

#164 Update Simulation to check for and write to cache
  benchmarking/caching/__init__.py
  benchmarking/caching/simulation_cache.py
  benchmarking/simulation/simulation.py
  benchmarking/simulation/simulation_settings.py
  requirements.txt
  tests/test_benchmarking/test_caching/__init__.py
  tests/test_benchmarking/test_caching/test_simulation_cache.py
Labels: enhancement

#171 Nested cache directories
  benchmarking/caching/simulation_cache.py
  tests/test_benchmarking/test_caching/test_simulation_cache.py
Labels: enhancement

#172 Continue cached simulations
  benchmarking/simulation/simulation.py
  tests/test_benchmarking/test_simulation/test_simulation.py
Labels: enhancement

#176 add cache keys to basic simulation set
  benchmarking/simulation/basic_simulation_set_2.py
  tests/test_benchmarking/test_simulation/test_basic_simulation_set_2.py
Labels: enhancement, blocking

#177 add mutation config
  api/ai/new/interfaces/algorithm_config.py
  api/ai/new/priority_algorithm/mutations/__init__.py
  api/ai/new/priority_algorithm/mutations/random_swap.py
  api/ai/new/priority_algorithm/priority_algorithm.py
  tests/test_api/test_ai/test_algorithm_runner.py
  tests/test_api/test_ai/test_priority_algorithm/test_priority_algorithm.py
Labels: enhancement, blocking
