Repository Teamable-Analytics/algorithms, pull requests merged in 2024-03, with the labels that each got.

#373 Refactor some API schema validation fields
  api/ai/interfaces/algorithm_options.py
  api/api/validators/evaluate_team_set_validator.py
  api/api/validators/generate_teams_validator.py
Labels: bug

#388 Adjustable length for DRR
  api/ai/double_round_robin_algorithm/double_round_robin_algorithm.py
Labels: bug, benchmarking

#387 Fix algorithm configs for algorithms needing utility_function
  api/ai/interfaces/algorithm_config.py
Labels: bug, benchmarking

#390 Add models and serializers for logging API calls
  .gitignore
  api/api/migrations/0001_initial.py
  api/api/migrations/__init__.py
  api/api/models/__init__.py
  api/api/models/base_models.py
  api/api/models/logs.py
  api/api/serializers/__init__.py
  api/api/serializers/logs.py
  api/api/settings/__init__.py
  docker-compose-dev.yml
  requirements.txt
Labels: api

#394 Add random slice mutation
  api/ai/priority_algorithm/mutations/random_slice.py
  tests/test_api/test_ai/test_priority_algorithm/test_mutations/test_random_slice.py
Labels: enhancement

#408 Log the /generate/teams endpoint
  api/api/__init__.py
  api/api/models/logs.py
  api/api/utils/response_with_metadata.py
  api/api/views/generate_teams.py
Labels: api
